### ISSUE TITLE
Construcción de la ventana 1 primera parte

### ISSUE THREAD

**Issue by sebasx200** [sebasx200/Clase_9#1]
Construir la ventana 1 y hacer el formulario para ingresar la información del cliente.

**Comment by sebasx200-1** [comment]
Hola, buenas tardes, yo me encargo entonces de esta funcionalidad.

**Comment by sebasx200** [comment]
Listo, se revisó issue y se cumplió con la tarea. Por favo revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario.
