### ISSUE TITLE
Construir en la ventana 1 el formulario para recuperar la contraseña

### ISSUE THREAD

**Issue by sebasx200** [sebasx200/Clase_9#2]
Hacer el formulario para recuperar la contraseña.
Esta funcionalidad va a la derecha de la ventana Ventana1().

**Comment by JuanPabloAngelC** [comment]
terminado , espero revision

**Comment by sebasx200** [comment]
Listo, mil gracias, se procede a finalizar issue, feliz y bendecida noche.
