### ISSUE TITLE
Construir en la ventana 1 el formulario para ingresar el usuario.

### ISSUE THREAD

**Issue by sebasx200** [sebasx200/Clase_9#4]
En este issue debes programar el botón de LIMPIAR para limpiar todos los campos. Además se debe hacer el formulario para pedir los datos del usuario.

**Comment by sebasx200-1** [comment]
Listo. Yo me encargo de este issue #4

**Comment by JuanPabloAngelC** [comment]
Issue solucionado, espero revision

**Comment by sebasx200** [comment]
Listo, muchas gracias.
