### ISSUE TITLE
Programar el botón para buscar las preguntas de recuperación de contraseña.

### ISSUE THREAD

**Issue by sebasx200** [sebasx200/Clase_9#6]
Validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña.
Validar que el documento sea un dato tipo numérico.
Crear la clase usuario con sus 11 propiedades.
Solo considerar una contraseña.
Buscar las preguntas para recuperar la contraseña.

**Comment by JuanPabloAngelC** [comment]
me voy a encargar de ello , que bendicion
pendiente de alguna sugerencia

**Comment by sebasx200** [comment]
Listo, qué bendición. Quedo pendiente de su primer push y pull request.

**Comment by sebasx200** [comment]
Se cierra este issue #1
